### ISSUE TITLE
Pre-trained vectors

### ISSUE THREAD

**Issue by ctbaumler** [yeonsw/OLIVE#1]
Your paper mentions publicly available pre-trained word vectors in addition to the source code. Do you plan to add these vectors to this repository, or are they available somewhere else?

**Comment by yeonsw** [comment]
This is the link to download the pre-trained word vectors and subword vectors.
https://www.dropbox.com/sh/o545xzooasmud0f/AADJLFee2BtGlCTNA6u0E4lda?dl=0

Thanks
